//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BuffTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BuffType), typeof(System.Object));
		L.RegFunction("New", _CreateBuffType);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("atknew", 1);
		L.RegConstant("defnew", 2);
		L.RegConstant("attnew", 3);
		L.RegConstant("levelnew", 4);
		L.RegConstant("racenew", 5);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateBuffType(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				BuffType obj = new BuffType();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: BuffType.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

