//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CardPositionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CardPosition), typeof(System.Object));
		L.RegFunction("New", _CreateCardPosition);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("deck", 10);
		L.RegConstant("extra", 11);
		L.RegConstant("grave", 12);
		L.RegConstant("except", 13);
		L.RegConstant("handcard", 14);
		L.RegConstant("area", 15);
		L.RegConstant("monster", 16);
		L.RegConstant("magictrap", 17);
		L.RegConstant("field", 18);
		L.RegConstant("special", 19);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCardPosition(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				CardPosition obj = new CardPosition();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: CardPosition.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

