//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DuelOperationWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DuelOperation), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetCardLocation", SetCardLocation);
		L.RegFunction("SetChainableEffect", SetChainableEffect);
		L.RegFunction("DrawCardOwn", DrawCardOwn);
		L.RegFunction("DrawCardOps", DrawCardOps);
		L.RegFunction("DrawnCard", DrawnCard);
		L.RegFunction("ShowCard", ShowCard);
		L.RegFunction("SpecialSummon", SpecialSummon);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("duelData", get_duelData, set_duelData);
		L.RegVar("cardPosition", get_cardPosition, set_cardPosition);
		L.RegVar("cardIndex", get_cardIndex, set_cardIndex);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCardLocation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.SetCardLocation(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetChainableEffect(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
				obj.SetChainableEffect(arg0);
				return 0;
			}
			else if (count == 3)
			{
				DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.SetChainableEffect(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DuelOperation.SetChainableEffect");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DrawCardOwn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.DrawCardOwn(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DrawCardOps(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.DrawCardOps(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DrawnCard(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.DrawnCard(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowCard(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ShowCard(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SpecialSummon(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DuelOperation obj = (DuelOperation)ToLua.CheckObject<DuelOperation>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SpecialSummon(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_duelData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DuelOperation obj = (DuelOperation)o;
			DuelDataManager ret = obj.duelData;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index duelData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cardPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DuelOperation obj = (DuelOperation)o;
			int ret = obj.cardPosition;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cardPosition on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cardIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DuelOperation obj = (DuelOperation)o;
			int ret = obj.cardIndex;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cardIndex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_duelData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DuelOperation obj = (DuelOperation)o;
			DuelDataManager arg0 = (DuelDataManager)ToLua.CheckObject<DuelDataManager>(L, 2);
			obj.duelData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index duelData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cardPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DuelOperation obj = (DuelOperation)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.cardPosition = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cardPosition on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cardIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DuelOperation obj = (DuelOperation)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.cardIndex = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cardIndex on a nil value");
		}
	}
}

