//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GamePhaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GamePhase), typeof(System.Object));
		L.RegFunction("New", _CreateGamePhase);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("turnstart", 0);
		L.RegConstant("draw", 10);
		L.RegConstant("standby", 20);
		L.RegConstant("main1", 30);
		L.RegConstant("battle", 40);
		L.RegConstant("battlestep", 41);
		L.RegConstant("damageStepStart", 42);
		L.RegConstant("damageCalBefore", 43);
		L.RegConstant("damageCalculate", 44);
		L.RegConstant("damageCalAfter", 45);
		L.RegConstant("damageStepEnd", 46);
		L.RegConstant("main2", 50);
		L.RegConstant("end", 60);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGamePhase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GamePhase obj = new GamePhase();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GamePhase.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

