//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameEvent), typeof(System.Object));
		L.RegFunction("New", _CreateGameEvent);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("drawcard", 1);
		L.RegConstant("selectcard", 2);
		L.RegConstant("normalsummon", 3);
		L.RegConstant("specialsummon", 4);
		L.RegConstant("changemean", 5);
		L.RegConstant("battle", 6);
		L.RegConstant("battledestroy", 7);
		L.RegConstant("effectdestroy", 8);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameEvent obj = new GameEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

